name: Docker CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build backend
        run: docker compose build backend

      - name: Build frontend
        run: docker compose build frontend

      - name: Wait for Postgres
        run: |
          echo "Waiting for Postgres to be ready..."
          for i in {1..10}; do
            if docker exec nasalanding-postgres-1 pg_isready -U user -d mydb; then
              echo "Postgres is ready!"
              break
            fi
            echo "Waiting..."
            sleep 3
          done


      - name: Run backend unit tests
        run: docker compose run --rm backend dotnet test --no-build --verbosity normal

      - name: Push backend image
        run: docker tag treetask-backend ghcr.io/${{ github.repository_owner }}/treetask-backend:latest && docker push ghcr.io/${{ github.repository_owner }}/treetask-backend:latest

      - name: Push frontend image
        run: docker tag treetask-frontend ghcr.io/${{ github.repository_owner }}/treetask-frontend:latest && docker push ghcr.io/${{ github.repository_owner }}/treetask-frontend:latest
